import { CATEGORIES, type GameDefinition } from "@/types";

export const GAMES: GameDefinition[] = [
  {
    id: "whoisundercoveragent",
    name: "臥底是誰？",
    nameEn: "Who Is Undercover?",
    description: "陣營心理戰，找出誰是臥底！",
    longDescription:
      "每個玩家拿到秘密詞彙，大部分人相同，只有臥底拿到的詞不同。透過問答和辯論，平民要找臥底，臥底要隱藏身份混入平民。",
    minPlayers: 4,
    maxPlayers: 12,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.PARTY,
    icon: "🕵️",
    color: "#9333ea",
    gradient: "linear-gradient(135deg, #9333ea, #ec4899)",
    tags: ["心理戰", "社交", "推理"],
    difficulty: "簡單",
  },
  {
    id: "bombcountdown",
    name: "炸彈倒數",
    nameEn: "Bomb Countdown",
    description: "超快節奏派對，炸彈誰來接？",
    longDescription:
      "同一條引信持續倒數，答對得 10 分並傳出炸彈，引信不重置！答錯扣 1 秒，爆炸者本局出局，最後倖存者加 50 分。下局全員回歸，比較多局累積積分。",
    minPlayers: 3,
    maxPlayers: 15,
    estimatedDuration: "3-8 分鐘",
    category: CATEGORIES.PARTY,
    icon: "💣",
    color: "#ef4444",
    gradient: "linear-gradient(135deg, #ef4444, #f97316, #ffe600)",
    tags: ["節奏", "反應", "派對"],
    difficulty: "簡單",
  },
  {
    id: "fireworkmaster",
    name: "煙火大師",
    nameEn: "Firework Master",
    description: "創意競賽，設計你的專屬煙火！",
    longDescription:
      "每位玩家在手機上設計專屬煙火（顏色、形狀、規模、特效），送出後在 TV 大螢幕上聯合施放壯觀煙火秀，大家投票評選最佳設計與最佳創意！",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.CREATIVE,
    icon: "🎆",
    color: "#00f0ff",
    gradient: "linear-gradient(135deg, #00f0ff, #bf00ff, #ff2d95)",
    tags: ["創意", "競賽", "視覺"],
    difficulty: "簡單",
  },
  {
    id: "everybodyknows",
    name: "大家心知肚明",
    nameEn: "Everybody Knows",
    description: "社交投票，看看誰和大家不一樣",
    longDescription:
      "主螢幕顯示趣味社交問題（如：「誰最容易在旅行中迷路？」），玩家在手機上匿名投票，大螢幕即時揭曉百分比統計與動態長條圖！",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.SOCIAL,
    icon: "🧠",
    color: "#39ff14",
    gradient: "linear-gradient(135deg, #39ff14, #00f0ff)",
    tags: ["社交", "投票", "互動"],
    difficulty: "簡單",
  },
  {
    id: "drawandguess",
    name: "你畫我猜",
    nameEn: "Draw & Guess",
    description: "塗鴉猜題，畫出你的想法！",
    longDescription:
      "所有玩家公平輪流作畫，筆跡邊畫邊同步到大螢幕。其他人看分類與逐步提示猜題，越快猜中得分越高（10–25 分），每有人猜中畫家加 5 分。",
    minPlayers: 4,
    maxPlayers: 16,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.CREATIVE,
    icon: "🎨",
    color: "#ff2d95",
    gradient: "linear-gradient(135deg, #ff2d95, #a855f7)",
    tags: ["塗鴉", "猜題", "創意"],
    difficulty: "中等",
  },
  {
    id: "realbattle",
    name: "大亂鬥",
    nameEn: "Real Battle",
    description: "手機當手把，主螢幕大亂鬥！",
    longDescription:
      "TV / iPad 顯示角色與地圖，玩家將手機作為無線遊戲手把（虛擬搖桿/按鈕），操控小角色搶奪金幣、星星與道具，最後分數最高者勝出！",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "3-10 分鐘",
    category: CATEGORIES.PARTY,
    icon: "⚔️",
    color: "#ff6b00",
    gradient: "linear-gradient(135deg, #ff6b00, #ff2d95)",
    tags: ["動作", "競技", "派對"],
    difficulty: "中等",
  },
  {
    id: "mysteryroom",
    name: "密室推理",
    nameEn: "Mystery Room",
    description: "合作解謎，拼湊真相！",
    longDescription:
      "每位玩家拿到不同的局部線索，大家必須透過口頭交流拼湊真相。主螢幕逐步揭露時間線與證物，合作解開案件！",
    minPlayers: 4,
    maxPlayers: 10,
    estimatedDuration: "10-20 分鐘",
    category: CATEGORIES.MYSTERY,
    icon: "🔍",
    color: "#a855f7",
    gradient: "linear-gradient(135deg, #a855f7, #6366f1)",
    tags: ["推理", "合作", "解謎"],
    difficulty: "困難",
  },
  {
    id: "aibullshit",
    name: "AI 瞎扯王",
    nameEn: "AI Bullshit",
    description: "吹牛大賽，看誰最會扯！",
    longDescription:
      "針對怪異問題，每位玩家在手機寫下煞有介事的假答案。系統混合真假答案後顯示於大螢幕，玩家投票猜測哪個才是真的！",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.PARTY,
    icon: "🤖",
    color: "#00f0ff",
    gradient: "linear-gradient(135deg, #00f0ff, #39ff14)",
    tags: ["搞笑", "吹牛", "社交"],
    difficulty: "簡單",
  },
  {
    id: "song3seconds",
    name: "三秒猜歌",
    nameEn: "3 Second Song Guess",
    description: "歌詞閃現 3 秒開搶，音樂達人決戰！",
    longDescription:
      "大螢幕 3 秒倒數後閃現一句關鍵歌詞（華語、J-Pop、西洋等），手機四選一搶答歌名！每 2 秒多解鎖 1 個字——拖得越久越容易，所以手速就是你的得分！答對 10 分，越快再最高加 15 分。",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "5-15 分鐘",
    category: CATEGORIES.MUSIC,
    icon: "🎵",
    color: "#ff2d95",
    gradient: "linear-gradient(135deg, #ff2d95, #bf00ff)",
    tags: ["音樂", "猜歌", "競賽"],
    difficulty: "中等",
  },
  {
    id: "kingtonight",
    name: "今晚誰是王",
    nameEn: "King Tonight",
    description: "快速挑戰，登基稱王！",
    longDescription:
      "輪流由一位玩家當「國王」發動挑戰（手速、反應、記憶、Emoji 猜題），全員在手機上快速競技，獲勝者登基為新國王！",
    minPlayers: 4,
    maxPlayers: 20,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.PARTY,
    icon: "👑",
    color: "#ffe600",
    gradient: "linear-gradient(135deg, #ffe600, #ff6b00, #ff2d95)",
    tags: ["挑戰", "反應", "王權"],
    difficulty: "簡單",
  },
  {
    id: "musicalchairs",
    name: "音樂椅",
    nameEn: "Musical Chairs",
    description: "音樂一停，搶不到椅子就出局！",
    longDescription:
      "大螢幕播放加速的節拍，每回合椅子總比人少一把。音樂停止前盡快點下「坐下」，點得最慢的人站着出局。撐到最後一把椅子的人稱王！",
    minPlayers: 3,
    maxPlayers: 20,
    estimatedDuration: "3-6 分鐘",
    category: CATEGORIES.PARTY,
    icon: "🪑",
    color: "#22d3ee",
    gradient: "linear-gradient(135deg, #22d3ee, #6366f1)",
    tags: ["反應", "淘汰", "經典"],
    difficulty: "簡單",
    rules: [
      "音樂播放時盯著大螢幕，節拍會越來越快",
      "音樂一停，立刻在手機點下「坐下」",
      "每回合椅子比人少一把，點得最慢的人出局",
      "每撐過一回合 +10 分，最後一位 +50 分",
      "任何人點「開始遊戲」可直接開玩",
    ],
  },
  {
    id: "whackmoles",
    name: "敲木頭",
    nameEn: "Whack-a-Mole",
    description: "木頭冒出來就敲，全場比誰敲得最多！",
    longDescription:
      "大螢幕 3×3 的洞會隨機冒出木頭，手機上是同樣的 3×3 網格。木頭出現時點對應的洞，每隻只能敲一次。三回合累加，總擊中數最高者獲勝，連續敲中 5 隻還有加碼！",
    minPlayers: 3,
    maxPlayers: 20,
    estimatedDuration: "3-5 分鐘",
    category: CATEGORIES.PARTY,
    icon: "🐹",
    color: "#f59e0b",
    gradient: "linear-gradient(135deg, #f59e0b, #ef4444)",
    tags: ["反應", "手速", "競賽"],
    difficulty: "簡單",
    rules: [
      "木頭從大螢幕的洞裡冒出來",
      "在手機上點「同樣位置」的洞才能敲中",
      "每隻木頭只能被敲一次，敲空洞不扣分",
      "連續敲中 5 隻，額外 +5 分",
      "3 回合累加，總分最高者獲勝",
    ],
  },
  {
    id: "simonsays",
    name: "西蒙說",
    nameEn: "Simon Says",
    description: "記住大螢幕的顏色順序，照著點出來！",
    longDescription:
      "大螢幕閃出一串四色方塊，盯緊了！閃完後在手機上照著順序點出來。每過一關序列就長一格，點錯一次本輪出局。三輪比賽，累積分數最高者拿下記憶王座。",
    minPlayers: 3,
    maxPlayers: 20,
    estimatedDuration: "5-10 分鐘",
    category: CATEGORIES.PARTY,
    icon: "🔷",
    color: "#818cf8",
    gradient: "linear-gradient(135deg, #818cf8, #ec4899)",
    tags: ["記憶", "專注", "淘汰"],
    difficulty: "中等",
    rules: [
      "大螢幕閃出的顏色順序要記住",
      "閃完後在手機上照順序點出來",
      "每過一關，序列會多一個顏色",
      "點錯一次，本輪出局",
      "3 輪累積分數，最高者獲勝",
    ],
  },
  {
    id: "wordchain",
    name: "文字接龍",
    nameEn: "Word Chain",
    description: "用上一個詞的最後一字接新詞，手快有！",
    longDescription:
      "大螢幕顯示一個詞，用它的「最後一字」開頭接出 2-4 個字的新詞，第一個有效接龍者得 10 分並成為新詞。不確定那是不是真詞？5 秒內按「異議」，全場投票判定！被推翻扣分、成功異議加分。",
    minPlayers: 3,
    maxPlayers: 20,
    estimatedDuration: "5-12 分鐘",
    category: CATEGORIES.SOCIAL,
    icon: "🀄",
    color: "#34d399",
    gradient: "linear-gradient(135deg, #34d399, #06b6d4)",
    tags: ["語言", "搶答", "投票"],
    difficulty: "中等",
    rules: [
      "用大螢幕詞的最後一字開頭接新詞（2-4 個中文字）",
      "第一個有效接龍者 +10 分，新詞成為新的接龍點",
      "同一詞不能重複用",
      "5 秒內可按「異議」，全場投票判定該詞有效與否",
      "成功異議 +5 分，被推翻 -5 分",
    ],
  },
  {
    id: "pokerlite",
    name: "快速撲克",
    nameEn: "Quick Poker",
    description: "五局德州撲克， bluff 到最後籌碼最多者獲勝！",
    longDescription:
      "每人 100 籌碼的德州撲克（翻牌前、翻牌、轉牌、河牌四條街），每個決策 15 秒，逾時面對下注自動棄牌，否則過牌。破產者下一局補 50 籌碼回來繼續開局。五局結束，籌碼最多者成為底鍋之王！",
    minPlayers: 3,
    maxPlayers: 8,
    estimatedDuration: "10-20 分鐘",
    category: CATEGORIES.SOCIAL,
    icon: "🃏",
    color: "#4f46e5",
    gradient: "linear-gradient(135deg, #4f46e5, #16a34a)",
    tags: ["策略", "心理戰", "賭術"],
    difficulty: "中等",
    rules: [
      "每人 100 籌碼，共 5 局，大盲 2 / 小盲 1 輪流",
      "四條街：翻牌前 → 翻牌 → 轉牌 → 河牌",
      "可棄牌、過牌、跟注或加注",
      "每個決策 15 秒，逾時面對下注棄牌，否則過牌",
      "籌碼用完的人下一局補 50 籌碼繼續",
      "五局後籌碼最多者獲勝",
    ],
  },
];
